### PR TITLE
Include icon font in deployment.

### PR DESCRIPTION
**Pull request by reitzig**
Avoid using web fonts, which can

 - cause problems with script blockers and 
	image

 - increase page load time.
    image

The potential advantage of cross-site caching does not apply for this custom font.

### CODE REVIEW

**Comment by reitzig** [comment]
I have deployed my blog now. See, for instance, [here](https://reitzig.github.io/today-i-learned/posts/2020-05-20-kotlin-native-in-ubi/):

image

As far as I can tell, iconfont.ttf is loaded successfully from fontbuf.com, is not blocked by any script blocker or the browser. The admonition icon font I included works just fine:

image

Whether or not the font comes from a third party doesn't make a difference; I tried locally with the downloaded font, no luck.
Can you reproduce, @cntrump (after refreshing caches)? 

My suspicion is that the character codes between CSS and the TTF got out of sync, but I'm not sure how to confirm that. I tried listing the codes included in the font, but couldn't find a suitable tool. The font might have to be rebuilt/-uploaded.

**Comment by cntrump** [comment]
Load webfoot from remote url because  demo `https://themes.gohugo.io/theme/hugo-notepadium/` host on `gohugo.io` can't find webfont correctly.

**Comment by reitzig** [comment]
Do I understand correctly: you include the font from a third-party location because gohugo.io doesn't work with static font assets?
If so, using a remote copy should maybe be an option, but surely not the default? :thinking: 

FWIW, doesn't work for the demo, either:
image

**Comment by cntrump** [comment]
static assets should loaded with abs path, like this: `url('/assets/font/iconfont.ttf')`

**Comment by cntrump** [comment]
> If so, using a remote copy should maybe be an option, but surely not the default? 🤔

Nice idea. but Hugo can't support template variables in CSS.

**Comment by reitzig** [comment]
> static assets should loaded with abs path, like this: `url('/assets/font/iconfont.ttf')`

I couldn't get that to work, neither with the file in `/static/` nor `/assets/font(s)`, that doesn't work.

 - When in `/assets/font(s)`, Hugo doesn't even copy over the font file to `public`.
 - When in `/static`, it is copied, but neither `url('admonition_icons.ttf')` nor `url('/admonition_icons.ttf')` work.

Maybe I'm missing something fundamental, but right now I don't know how to do what you suggest.

> > If so, using a remote copy should maybe be an option, but surely not the default? thinking
> 
> Nice idea. but Hugo can't support template variables in CSS.

But [it can](https://github.com/cntrump/hugo-notepadium/pull/85)! :D

**Comment by cntrump** [comment]
> But [it can](https://github.com/cntrump/hugo-notepadium/pull/85)! :D

Nice! Updated

```toml
[params]
internalIconfont = true
```

**Comment by reitzig** [comment]
> Maybe I'm missing something fundamental, but right now I don't know how to do what you suggest.

[This](https://discourse.gohugo.io/t/how-to-load-assets-from-the-static-folder-in-a-css-file/21005/4?u=reitzig) applies:

> if you [start urls with a dot] then the browswer will load the font files from a relative directory, rather than working a directory based on web root.

:man_facepalming:

**Comment by cntrump** [comment]
Merged https://github.com/cntrump/hugo-notepadium/pull/85

**Comment by reitzig** [comment]
> man_facepalming


_Update:_ Nope, didn't work either. Using `{{ .Site.BaseURL }}` seems advised. I'll note that my site lives in a subfolder and I compensate by adding `<base href="{{ .Site.BaseURL }}">` to  `<head>`; can that have an impact?

**Comment by cntrump** [comment]
> > man_facepalming
> 
> _Update:_ Nope, didn't work either. Using `{{ .Site.BaseURL }}` seems advised. I'll note that my site lives in a subfolder and I compensate by adding `<base href="{{ .Site.BaseURL }}">` to `<head>`; can that have an impact?

404 for `https://reitzig.github.io/today-i-learned/css/admonition_icons.ttf`
static assets host on GitHub.io needs a custom domain, or you can try [netlify](https://www.netlify.com/).

**Comment by reitzig** [comment]
> 404 for `https://reitzig.github.io/today-i-learned/css/admonition_icons.ttf`
> static assets host on GitHub.io needs a custom domain, or you can try [netlify](https://www.netlify.com/).

Since both `url('../assets/font/admonition_icons.ttf')` and `url('{{- .Site.BaseURL -}}/assets/font/admonition_icons.ttf')` do that, why would I do that?

The version I had deployed when you commented was broken, yes. Fix deployed now, with the theme on revision e376c8b885603cb809834f07ce02440ebfd7c152. And still:

image

We see the effect of `src:url(/assets/font/iconfont.ttf?t=1588390362269)` vs `src:url(https://reitzig.github.io/today-i-learned//assets/font/admonition_icons.ttf)`.
--> https://github.com/cntrump/hugo-notepadium/pull/88

**Pull request closed without merging**
